#!/usr/bin/env python3
import os
import re
import glob
from datetime import datetime
import yaml

# Function to extract frontmatter from markdown files
def extract_frontmatter(file_path):
    with open(file_path, 'r', encoding='utf-8') as file:
        content = file.read()
    
    # Extract frontmatter
    frontmatter_match = re.match(r'^---\n(.*?)\n---', content, re.DOTALL)
    if frontmatter_match:
        frontmatter_text = frontmatter_match.group(1)
        try:
            frontmatter = yaml.safe_load(frontmatter_text)
            return frontmatter
        except yaml.YAMLError:
            return {}
    return {}

# Function to extract excerpt from markdown files
def extract_excerpt(file_path):
    with open(file_path, 'r', encoding='utf-8') as file:
        content = file.read()
    
    # Remove frontmatter
    content = re.sub(r'^---\n.*?\n---', '', content, flags=re.DOTALL).strip()
    
    # Check for explicit excerpt marker
    excerpt_match = re.search(r'<!-- more -->', content)
    if excerpt_match:
        excerpt = content[:excerpt_match.start()].strip()
    else:
        # Take first paragraph
        paragraph_match = re.search(r'^# .*?\n\n(.*?)(\n\n|$)', content, re.DOTALL)
        if paragraph_match:
            excerpt = paragraph_match.group(1).strip()
        else:
            # Just take the first 200 characters
            excerpt = content[:200].strip() + '...'
    
    return excerpt

# Get all blog posts
blog_posts = []
for post_file in glob.glob('docs/blog/posts/*.md'):
    frontmatter = extract_frontmatter(post_file)
    
    if 'date' in frontmatter:
        date_str = frontmatter['date']
        if isinstance(date_str, str):
            try:
                date = datetime.strptime(date_str, '%Y-%m-%d')
            except ValueError:
                continue
        else:
            date = date_str
        
        # Get post title
        with open(post_file, 'r', encoding='utf-8') as file:
            content = file.read()
            title_match = re.search(r'^# (.*?)$', content, flags=re.MULTILINE)
            title = title_match.group(1) if title_match else os.path.basename(post_file).replace('.md', '')
        
        # Get post URL based on title (slug)
        slug = title.lower().replace(' ', '-').replace(':', '').replace('?', '').replace('!', '').replace('.', '').replace(',', '')
        post_url = f"blog/{date.strftime('%Y/%m/%d')}/{slug}/"
        
        # Get image path
        image_path = frontmatter.get('image', f"assets/images/blog/{os.path.basename(post_file).replace('.md', '')}.svg")
        
        # Get description
        description = frontmatter.get('description', extract_excerpt(post_file))
        
        # Format date for display
        display_date = date.strftime('%b %d, %y')
        
        blog_posts.append({
            'title': title,
            'date': date,
            'display_date': display_date,
            'image': image_path,
            'description': description,
            'url': post_url
        })

# Sort posts by date (newest first)
blog_posts.sort(key=lambda x: x['date'], reverse=True)

# Take the latest 6 posts (or all if less than 6)
latest_posts = blog_posts[:6]

# Generate the home page content
home_page_content = """---
hide:
  - toc
---

<!-- 
This file is automatically generated by update_home_page.py during deployment.
Any changes made directly to this file will be overwritten.
-->

<div class="main-container">
  <div class="hero-container">
    <div class="hero-content">
      <h1 class="hero-title">Hi, I'm Alan Liang.</h1>
      <p class="hero-bio">I architect and scale cloud infrastructure at Commonwealth Bank of Australia, specializing in AWS, DevOps, and Kubernetes solutions. I love solving complex distributed systems challenges and mentoring teams on cloud-native best practices.</p>
      
      <div class="social-links">
        <a href="https://github.com/alanliangdev" class="social-link" aria-label="GitHub">
          <i class="fab fa-github"></i>
        </a>
        <a href="https://www.linkedin.com/in/alanliangdev/" class="social-link" aria-label="LinkedIn">
          <i class="fab fa-linkedin-in"></i>
        </a>
      </div>
    </div>
    
    <div class="hero-image">
      <img src="assets/images/profile-photo.jpeg" alt="Alan Liang">
    </div>
  </div>

  <div class="blog-grid">
"""

# Add each post to the home page in a card format
for post in latest_posts:
    home_page_content += f"""    <div class="blog-card">
      <a href="{post['url']}" class="blog-card-link">
        <div class="blog-card-image" style="background-image: url('{post['image']}')">
          <div class="blog-card-date">{post['display_date']}</div>
        </div>
        <h3 class="blog-card-title">{post['title']}</h3>
        <p class="blog-card-description">{post['description'][:100]}...</p>
      </a>
    </div>
"""

home_page_content += """  </div>
</div>

<div class="site-footer">
  © 2025 Alan Liang
</div>"""

# Write the home page content to index.md
with open('docs/index.md', 'w', encoding='utf-8') as file:
    file.write(home_page_content)

print("Home page updated with the latest blog posts in card format!")